/*****************************************************************************\

Copyright (C) 2013, GTA-Network Team <contact at gta-network dot net>

This software is provided 'as-is', without any express or implied
warranty.  In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
claim that you wrote the original software. If you use this software
in a product, an acknowledgment in the product documentation would be
appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be
misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.

\*****************************************************************************/

#ifndef GTAV_H
#define GTAV_H

typedef unsigned int u32; typedef int i32;
typedef unsigned short u16; typedef short i16;
typedef unsigned char u8; typedef char i8, ch; typedef wchar_t wch;
typedef float f32; typedef double f64;
typedef bool b8; typedef unsigned int b32;
typedef void * ptr; typedef unsigned char BYTE;

template <typename T>
inline T *ptr_cast(u32 value) {
	return *reinterpret_cast<T **>(&value);
}

inline ptr ptr_cast(u32 value){
	return *reinterpret_cast<ptr*>(&value);
}

template <class T>
inline T* ptr_cast(ptr value){
	return reinterpret_cast<T*>(value);
}


#ifndef NULL
#define NULL (0)
#endif

namespace eGTAVSpace
{
	unsigned uiVersion = NULL;
	enum eVersion
	{
		VERSION_BETA,		// 1
		VERSION_X360,		// 2
		VERSION_PS3,		// 3
		VERSION_PC,			// 4
		VERSION_ORBIS,		// 5
		VERSION_NONFINAL	// 6
	};
	eVersion	GetVersion(BYTE byteVersion) { return (eVersion) byteVersion; }
	void		SetVersion(unsigned uiVersionEAX) { uiVersion = uiVersionEAX; }

	enum eVVehicleTypes
	{
		BICYCLE,	// 0
		CAR,		// 1
		QUADBIKE,	// 2
		BIKE,		// 3
		BOAT,		// 4
		TRAIN,		// 5
		HELI,		// 6
		PLANE,		// 7
		AUTOGYRO,	// 8
		SUBMARINE,	// 9
		TRAILER,	// 10
		BLIMP		// 11
	};

	enum eVBlips {
		BLIP_OTHPLAYER,
		BLIP_PROPCAT,
		BLIP_PLAYER,
		BLIP_DEST,
		BLIP_COP,
		BLIP_PICK,
		BLIP_GALLERY,
		BLIP_ENEMY,
		BLIP_CAR,
		BLIP_PICK_OBJ,
		BLIP_CONT,
		BLIP_FRIEND,
		BLIP_TREV,
		BLIP_MICHAEL,
		BLIP_FRANKLIN
	};

	enum eVMapTypes {
		MAP_VISLOW,
		MAP_VISHIGH,
		MAP_GOLF,
		MAP_INTERIOR,
		MAP_CANSTARTMISS,
		MAP_CANDROPPOI,
		MAP_CANZOOM,
		MAP_WAYPOINT,
		MAP_CANWARP
	};

	enum eVPedModels {
		GTAV_MP_PLAYER
	};

	enum eVStreamerPrioritys {
		PRIO_LOWEST,
		PRIO_BELOW_NORMAL,
		PRIO_NORMAL,
		PRIO_IDLE,
		PRIO_ABOVE_NORMAL,
		PRIO_HIGHEST
	};


	enum eVPools {
		AnimatedBuilding, // Size: 210
		AttachmentExtension, // Size: 290
		BlendshapeStore, // Size: 75
		Building, // Size: 28500
		carrec, // Size: 3700
		CBoatChaseDirector, // Size: 4
		CVehicleCombatAvoidanceArea, // Size: 5
		CCargen, // Size: 750
		CCargenForScenarios, // Size: 150
		CCombatDirector, // Size: 5
		CCombatInfo, // Size: 16
		CCombatSituation, // Size: 6
		CCoverFinder, // Size: 40
		CDefaultCrimeInfo, // Size: 13
		CTacticalAnalysis, // Size: 3
		AnimStore, // Size: 9750
		CGameScriptResource, // Size: 1500
		ClothStore, // Size: 60
		CombatMeleeManager_Groups, // Size: 3
		CombatMountedManager_Attacks, // Size: 1
		CompEntity, // Size: 39
		CPrioritizedClipSetBucked, // Size: 22
		CPrioritizedClipSetRequest, // Size: 106
		CRoadBlock, // Size: 3
		CStuntJump, // Size: 64
		CScenarioInfo, // Size: 64
		CScenarioPointExtraData, // Size: 220
		CutsceneStore, // Size: 400
		CScriptEntityExtension, // Size: 150
		CVehicleChaseDirector, // Size: 4
		CVehicleClipRequestHelper, // Size: 45
		CPathNodeRouteSearchHelper, // Size: 119
		CGrabHelper, // Size: 8
		CGpsNumNodesStored, // Size: 1024
		CClimbHandHoldDetected, // Size: 16
		CAmbientLookAt, // Size: 40
		DrawableStore, // Size: 50000
		DummyObject, // Size: 8000
		DwdStore, // Size: 10650
		EntityBatch, // Size: 5000
		GrassBatch, // Size: 5000
		ExprDictStore, // Size: 190
		FrameFilterStore, // Size: 14
		FragmentStore, // Size: 4255
		GamePlayerBroadcastDataHandler_Remote, // Size: 500
		InteriorInst, // Size: 80
		InteriorProxy, // Size: 475
		IplStore, // Size: 3000
		MaxLoadedInfo, // Size: 6000
		MaxLoadRequestedInfo, // Size: 3000
		ActiveLoadedInfo, // Size: 3000
		ActivePersistentLoadedInfo, // Size: 1439
		KnownRefs, // Size: 11500
		LightEntity, // Size: 2000
		MapDataLoadedNode, // Size: 566
		MapDataStore, // Size: 4300
		MapTypesStore, // Size: 800
		MetaDataStore, // Size: 1551
		NavMeshes, // Size: 10100
		NetworkDefStore, // Size: 118
		NetworkCewDataMgr, // Size: 16
		Object, // Size: 800
		OcclusionInteriorInfo, // Size: 50
		OcclusionPortalEntity, // Size: 163
		OcclusionPortalInfo, // Size: 250
		Peds, // Size: 110
		ScenarioPedsMultiplier, // Size: 100
		AmbientPedsMultiplier, // Size: 100
		MaxTotalPeds, // Size: 100
		CWeapon, // Size: 117
		phInstGTA, // Size: 2214
		PhysicsBounds, // Size: 1450
		CPickup, // Size: 73
		CPickupPlacement, // Size: 280
		CPickupPlacementCustomScriptData, // Size: 60
		CRegenerationInfo, // Size: 56
		PedMemoryMultiplier, // Size: 500
		PedsForVehicles, // Size: 75
		PortalInst, // Size: 95
		PoseMatcherStore, // Size: 20
		PMStore, // Size: 100
		PtFxSortedEntity, // Size: 30
		PtFxAssetStore, // Size: 250
		QuadTreeNodes, // Size: 1310
		ScaleformStore, // Size: 642
		ScaleformMgrArray, // Size: 40
		ScriptStore, // Size: 780
		StaticBounds, // Size: 10520
		tcBox, // Size: 1300
		TrafficLightInfos, // Size: 84
		TxdStore, // Size: 27300
		Vehicles, // Size: 148
		VehicleAmbientDensityMultiplier, // Size: 100
		VehicleMemoryMultiplier, // Size: 300
		VehicleParkedDensityMultiplier, // Size: 100
		VehicleStreamRequest, // Size: 30
		VehicleStreamRender, // Size: 35
		VehicleStruct, // Size: 53
		VehicleUpperLimit, // Size: 60
		VehicleUpperLimitMP, // Size: 20
		VehicleKeyholeShapeInnerThickness, // Size: 50
		VehicleKeyholeShapeOuterThickness, // Size: 60
		VehicleKeyholeShapeInnerRadius, // Size: 50
		VehicleKeyholdShapeOuterRadius, // Size: 165
		VehicleKeyholdSideWallThickness, // Size: 60
		VehicleMaxCreationDistance, // Size: 225
		VehicleMaxCreationDistanceOffscreen, // Size: 50
		VehicleCullRange, // Size: 251
		VehicleCullRangeOffScreen, // Size: 100
		DensityBasedRemovalRateScale, // Size: 36
		DensityBasedRemovalTargetHeadroom, // Size: 10
		VehicleSpacing_0, // Size: 1
		VehicleSpacing_1, // Size: 172
		VehicleSpacing_2, // Size: 150
		VehicleSpacing_3, // Size: 129
		VehicleSpacing_4, // Size: 110
		VehicleSpacing_5, // Size: 88
		VehicleSpcaing_6, // Size: 55
		VehicleSpacing_7, // Size: 52
		VehicleSpacing_8, // Size: 45
		VehicleSpacing_9, // Size: 40
		VehicleSpacing_10, // Size: 34
		VehicleSpacing_11, // Size: 27
		VehicleSpacing_12, // Size: 22
		VehicleSpacing_13, // Size: 20
		VehicleSpcaing_14, // Size: 19
		VehicleSpacing_15, // Size: 18
		PlayersRoadScanDistance, // Size: 300
		PlayerRoadDensityInc_0, // Size: 0
		PlayerRoadDensityInc_1, // Size: 0
		PlayerRoadDensityInc_2, // Size: 0
		PlayerRoadDensityInc_3, // Size: 0
		PlayerRoadDensityInc_4, // Size: 0
		PlayerRoadDensityInc_5, // Size: 0
		PlayerRoadDensityInc_6, // Size: 0
		PlayerRoadDensityInc_7, // Size: 0
		PlayerRoadDensityInc_8, // Size: 0
		PlayerRoadDensityInc_9, // Size: 0
		PlayerRoadDensityInc_10, // Size: 0
		PlayerRoadDensityInc_11, // Size: 0
		PlayerRoadDensityInc_12, // Size: 0
		PlayerRoadDensityInc_13, // Size: 0
		PlayerRoadDensityInc_14, // Size: 0
		PlayerRoadDensityInc_15, // Size: 0
		NonPlayerRoadDensityDec_1, // Size: 0
		NonPlayerRoadDensityDec_2, // Size: 0
		NonPlayerRoadDensityDec_3, // Size: 1
		NonPlayerRoadDensityDec_4, // Size: 1
		NonPlayerRoadDensityDec_5, // Size: 1
		NonPlayerRoadDensityDec_6, // Size: 1
		NonPlayerRoadDensityDec_7, // Size: 2
		NonPlayerRoadDensityDec_8, // Size: 2
		NonPlayerRoadDensityDec_9, // Size: 2
		NonPlayerRoadDensityDec_10, // Size: 2
		NonPlayerRoadDensityDec_11, // Size: 2
		NonPlayerRoadDensityDec_12, // Size: 3
		NonPlayerRoadDensityDec_13, // Size: 3
		NonPlayerRoadDensityDec_14, // Size: 3
		NonPlayerRoadDensityDec_15, // Size: 3
		VehiclePopulationFrameRate, // Size: 25
		VehiclePopulationCyclesPerFrame, // Size: 1
		wptrec, // Size: 768
		fwLodNode, // Size: 12500
		CTask, // Size: 1450
		CEvent, // Size: 500
		CMoveObject, // Size: 112
		CMoveAnimatedBuilding, // Size: 161
		atDScriptObjectNode, // Size: 450
		fwDynamicArchetypeComponent, // Size: 6830
		fwDynamicEntityComponent, // Size: 1000
		fwEntityContainer, // Size: 615
		fwMatrixTransform, // Size: 1536
		fwQuaternionTransform, // Size: 12958
		fwSimpleTransform, // Size: 30720
		ScenarioCarGensPerRegion, // Size: 80
		ScenarioPointsAndEdgesPerRegion, // Size: 1000
		ScenarioPoint, // Size: 900
		ScenarioPointEntity, // Size: 350
		ScenarioPointWorld, // Size: 1400
		MaxNonRegionScenarioPointSpatialObjects, // Size: 900
		ObjectIntelligence, // Size: 37
		VehicleScenarioAttractors, // Size: 64
		AircraftFlames, // Size: 34
		CScenarioPointChainUseInfo, // Size: 76
		CScenarioClusterSpawnedTrackingData, // Size: 190
		CSPClusterFSMWrapper, // Size: 192
		fwArchetypePooledMap, // Size: 36497
		CTaskConversationHelper, // Size: 4
		SyncedScenes, // Size: 10
		CPropManagementHelper, // Size: 77
		ActionTable_Definitions, // Size: 271
		ActionTable_Results, // Size: 426
		ActionTable_Impulses, // Size: 20
		ActionTable_Interrelations, // Size: 60
		ActionTable_Homings, // Size: 156
		ActionTable_Damages, // Size: 21
		ActionTable_StrikeBones, // Size: 15
		ActionTable_Rumbles, // Size: 5
		ActionTable_Branches, // Size: 15
		ActionTable_StealthKills, // Size: 10
		ActionTable_Vfx, // Size: 30
		ActionTable_FacialAnimSets, // Size: 5
		NetworkEntityAreas, // Size: 64
		NavMeshRoute // Size: 113
	};

	enum eVPADStates {
		PAD_RSTICK_DOWN,
		PAD_RSTICK_UP,
		PAD_RSTICK_LEFT,
		PAD_DPAD_NONE,
		PAD_DPAD_UPDOWN,
		PAD_DPAD_ALL,
		PAD_LSTICK_DOWN,
		PAD_LSTICK_UP,
		PAD_LSTICk_LEFT,
		PAD_DPAD_DOWN,
		PAD_DPAD_UP,
		PAD_LSTICK_ALL,
		PAD_DPAD_LEFT,
		PAD_DPAD_RIGHT,
		PAD_RSTICK_ALL,
		PAD_RSTICK_NONE,
		PAD_LSTICK_RIGHT,
		PAD_RSTICK_ROTATE,
		PAD_LSTICK_NONE,
		PAD_RSTICK_UPDOWN,
		PAD_LSTICK_UPDOWN,
		PAD_LSTICK_ROTATE,
		PAD_DPAD_LEFTRIGHT,
		PAD_RSTICK_LEFTRIGHT,
		PAD_RSTICK_RIGHT,
		PAD_LSTICK_LEFTRIGHT
	};

	enum eVMenuIDs {
		MENU_UNIQUE_ID_SETTINGS_CAMERA,
		MENU_UNIQUE_ID_HOME_NEWSWIRE,
		MENU_UNIQUE_ID_CUTSCENE_EMPTY,
		MENU_UNIQUE_ID_REPLAY_RANDOM,
		MENU_UNIQUE_ID_SETTINGS_SIXAXIS,
		MENU_UNIQUE_ID_INCEPT_TRIGGER,
		MENU_UNIQUE_ID_BETTING_LOBBYLIST,
		MENU_UNIQUE_ID_BETTING_INFOLIST,
		MENU_UNIQUE_ID_BETTING,
		MENU_UNIQUE_ID_HEADER_BETTING,
		MENU_UNIQUE_ID_RACE_LOBBYLIST,
		MENU_UNIQUE_ID_RACE_INFOLIST,
		MENU_UNIQUE_ID_RACE_INFO,
		MENU_UNIQUE_ID_HEADER_RACE,
		MENU_UNIQUE_ID_CREW_REQUEST,
		MENU_UNIQUE_ID_HOME_OPEN_JOBS,
		MENU_UNIQUE_ID_CREW_LEADERBOARDS,
		MENU_UNIQUE_ID_CORONA_INVITE_LAST_JOB_PLAYERS,
		MENU_UNIQUE_ID_CORONA_INVITE_MATCHED_PLAYERS,
		MENU_UNIQUE_ID_HEADER_CORONA_INVITE_LAST_JOB_PLAYERS,
		MENU_UNIQUE_ID_HEADER_CORONA_INVITE_MATCHED_PLAYERS,
		MENU_UNIQUE_ID_CORONA_JOINED_LIST,
		MENU_UNIQUE_ID_CORONA_INVITE_LIST,
		MENU_UNIQUE_ID_CORONA_DETAILS_LIST,
		MENU_UNIQUE_ID_CORONA_SETTINGS_LIST,
		MENU_UNIQUE_ID_HEADER_JOINING_SCREEN,
		MENU_UNIQUE_ID_SETTINGS_FACEBOOK,
		MENU_UNIQUE_ID_CORONA_INVITE_CREWS,
		MENU_UNIQUE_ID_CORONA_INVITE_FRIENDS,
		MENU_UNIQUE_ID_CORONA_INVITE_PLAYERS,
		MENU_UNIQUE_ID_CORONA_JOINED_PLAYERS,
		MENU_UNIQUE_ID_HEADER_CORONA_INVITE_CREWS,
		MENU_UNIQUE_ID_HEADER_CORONA_INVITE_FRIENDS,
		MENU_UNIQUE_ID_HEADER_CORONA_INVITE_PLAYERS,
		MENU_UNIQUE_ID_HEADER_CORONA_JOINED_PLAYERS,
		MENU_UNIQUE_ID_HEADER_CORONA_LOBBY,
		MENU_UNIQUE_ID_HEADER_CORONA,
		MENU_UNIQUE_ID_LOBBY_LIST_ITEM,
		MENU_UNIQUE_ID_LOBBY_LIST,
		MENU_UNIQUE_ID_HEADER_TEXT_SELECTION,
		MENU_UNIQUE_ID_BRIGHTNESS_CALIBRATION,
		MENU_UNIQUE_ID_GALLERY_OPTIONS_LIST,
		MENU_UNIQUE_ID_GALLERY_OPTIONS,
		MENU_UNIQUE_ID_SETTINGS_FEED,
		MENU_UNIQUE_ID_HEADER_EMPTY,
		MENU_UNIQUE_ID_HOME_DIALOG,
		MENU_UNIQUE_ID_TEAM_SELECT,
		MENU_UNIQUE_ID_FRIENDS_MP,
		MENU_UNIQUE_ID_FRIENDS_OPTIONS_LIST,
		MENU_UNIQUE_ID_CREW_OPTIONS_LIST,
		MENU_UNIQUE_ID_CREW_OPTIONS,
		MENU_UNIQUE_ID_PARTY_OPTIONS_LIST,
		MENU_UNIQUE_ID_PARTY_OPTIONS,
		MENU_UNIQUE_ID_PLAYERS_OPTIONS_LIST,
		MENU_UNIQUE_ID_PLAYERS_OPTIONS,
		MENU_UNIQUE_ID_PLAYERS_LIST,
		MENU_UNIQUE_ID_CREATION_LIFESTYLE_LIST,
		MENU_UNIQUE_ID_CREATION_HERITAGE_LIST,
		MENU_UNIQUE_ID_CREW,
		MENU_UNIQUE_ID_REPLAY_MISSION_ACTIVITY,
		MENU_UNIQUE_ID_REPLAY_MISSION_LIST,
		MENU_UNIQUE_ID_REPLAY_MISSION,
		MENU_UNIQUE_ID_PARTY_LIST,
		MENU_UNIQUE_ID_CREATION_YOU,
		MENU_UNIQUE_ID_CREATION_LIFESTYLE,
		MENU_UNIQUE_ID_CREATION_HERITAGE,
		MENU_UNIQUE_ID_HEADER_MP_CHARACTER_CREATION,
		MENU_UNIQUE_ID_HEADER_MP_CHARACTER_SELECT,
		MENU_UNIQUE_ID_FRIENDS_OPTIONS,
		MENU_UNIQUE_ID_FRIENDS_LIST,
		MENU_UNIQUE_ID_MISSION_CREATOR_STAT,
		MENU_UNIQUE_ID_MISSION_CREATOR_LISTITEM,
		MENU_UNIQUE_ID_MISSION_CREATOR_CATEGORY,
		MENU_UNIQUE_ID_CREW_LIST,
		MENU_UNIQUE_ID_CREW_INVITES,
		MENU_UNIQUE_ID_CREW_FRIENDS,
		MENU_UNIQUE_ID_CREW_ROCKSTAR,
		MENU_UNIQUE_ID_CREW_MINE,
		MENU_UNIQUE_ID_STATS_LISTITEM,
		MENU_UNIQUE_ID_SPECTATOR,
		MENU_UNIQUE_ID_CREWS_CARD,
		MENU_UNIQUE_ID_CREWS_FILTER,
		MENU_UNIQUE_ID_CREWS_CATEGORY,
		MENU_UNIQUE_ID_MAP_LEGEND,
		MENU_UNIQUE_ID_SAVE_GAME_LIST,
		MENU_UNIQUE_ID_SETTINGS_LIST,
		MENU_UNIQUE_ID_STATS_CATEGORY,
		MENU_UNIQUE_ID_PLACEHOLDER,
		MENU_UNIQUE_ID_LOBBY,
		MENU_UNIQUE_ID_PARTY,
		MENU_UNIQUE_ID_HEADER_LOBBY,
		MENU_UNIQUE_ID_HEADER_PRE_LOBBY,
		MENU_UNIQUE_ID_LEAVE_GAME,
		MENU_UNIQUE_ID_GAME_MP,
		MENU_UNIQUE_ID_MISSION_CREATOR,
		MENU_UNIQUE_ID_HEADER_MY_MP,
		MENU_UNIQUE_ID_HEADER_MULTIPLAYER,
		MENU_UNIQUE_ID_MP_CHAR_5,
		MENU_UNIQUE_ID_MP_CHAR_4,
		MENU_UNIQUE_ID_MP_CHAR_3,
		MENU_UNIQUE_ID_MP_CHAR_2,
		MENU_UNIQUE_ID_MP_CHAR_1,
		MENU_UNIQUE_ID_FREEMODE,
		MENU_UNIQUE_ID_GALLERY_ITEM,
		MENU_UNIQUE_ID_SETTINGS_SAVEGAME,
		MENU_UNIQUE_ID_CREWS,
		MENU_UNIQUE_ID_HOME,
		MENU_UNIQUE_ID_HEADER_SAVE_GAME,
		MENU_UNIQUE_ID_HEADER,
		MENU_UNIQUE_ID_SAVE_GAME,
		MENU_UNIQUE_ID_LOAD_GAME,
		MENU_UNIQUE_ID_NEW_GAME,
		MENU_UNIQUE_ID_SETTINGS_CONTROLS,
		MENU_UNIQUE_ID_SETTINGS_DISPLAY,
		MENU_UNIQUE_ID_SETTINGS_AUDIO,
		MENU_UNIQUE_ID_HOME_FEED,
		MENU_UNIQUE_ID_HOME_BRIEF,
		MENU_UNIQUE_ID_HOME_HELP,
		MENU_UNIQUE_ID_STORE,
		MENU_UNIQUE_ID_CORONA_INVITE,
		MENU_UNIQUE_ID_CORONA_SETTINGS,
		MENU_UNIQUE_ID_HOME_MISSION,
		MENU_UNIQUE_ID_LOST,
		MENU_UNIQUE_ID_COPS,
		MENU_UNIQUE_ID_VAGOS,
		MENU_UNIQUE_ID_AVAILABLE,
		MENU_UNIQUE_ID_STATS,
		MENU_UNIQUE_ID_MEDALS,
		MENU_UNIQUE_ID_WEAPONS,
		MENU_UNIQUE_ID_PLAYERS,
		MENU_UNIQUE_ID_SETTINGS,
		MENU_UNIQUE_ID_GAME,
		MENU_UNIQUE_ID_SOCIALCLUB,
		MENU_UNIQUE_ID_GALLERY,
		MENU_UNIQUE_ID_FRIENDS,
		MENU_UNIQUE_ID_INFO,
		MENU_UNIQUE_ID_START,
		MENU_UNIQUE_ID_MAP,
		MENU_UNIQUE_ID_INVALID,
	};

	enum eVScriptVMNatives {
		SET_PLAYER_ARMOUR,
		SET_PLAYER_HEALTH,
		REMOVE_SAVING,
		SET_DISPLAY_CONFIG,
		SET_MINIMAP_VISIBLE_STATE,
		SET_HELPTEXT_HEIGHT,
		SET_IMPORTANT_PARAMS,
		REMOVE_HUD_ITEM,
		MULTIPLAYER_IS_ACTIVE,
		FLASH_HEALTH_BAR,
		SET_CHARACTER_COLOUR,
		SET_ABILITY_BAR,
		FLASH_ABILITY_BAR,
		BLINK_ABILITY_BAR,
		SET_AIR_BAR,
		OVERRIDE_COMPONENT_POSITION,
		SHOW_STALL_WARNIG,
		TOGGLE_COMPONENT,
		FLASH_MINIMAP,
		GET_ASSET_ARRAY,
		REGISTER_HEALTH_ARMOUR,
		REGISTER_MAP_LAYER,
		STOP_BLIP_FLASHING,
		START_BLIP_FLASHING,
		SHOW_AIRCRAFT_COMPONENTS,
		GOLF_LINK,
		SHUTDOWN_MOVIE,
		SET_DATA_SLOT_EMPTY,
		SET_INPUT_EVENT_CROSS,
		SET_INPUT_EVENT_CIRCLE,
		GET_CURRENT_COLOUMN,
		SET_INPUT_EVENT,
		GET_CURRENT_SELECTION,
		HIDE_BUTTONS,
		HAS_NO_MEMBERS,
		STOP_FLASHING_WANTED_OVERLAY,
		FLASH_WANTED_OVERLAY,
		IS_WAYPOIT_SET,
		GET_CURRENT_END_INDEX,
		GET_CURRENT_START_INDEX,
		SET_INPUT_EVENT_TRIANGLE,
		FADE_TO_BLACK,
		HIGHLIGHT_ITEM,
		SET_ANALOG_STICK_INPUT,
		TXT_ALREADY_LOADED,
		RESTART_MOVIE,
		PAUSE_MENU_SP_CONTENT,
		SET_COLUMN_TITLE,
		SET_SAVING_TEXT,
		REMOVE_STREAM_COMPONENT,
		SET_STREAM_COMPONENT,
		SET_COMPONENT_VALUES,
		SET_COMPONENT_POSITION,
		SELECT_RADIO_STATION,
		SET_PLAYER_WEAPON_WHEEL,
		SET_POITER,
		START_CROSSFADE,
		SET_STATS_VISIBILITY,
		PM_RANGE,
		PM_ACCURACY,
		PM_FIRERATE,
		PM_DAMAGE,
		SET_STATS_LABLES_AND_VALUES,
		SET_ATTACHMENTS,
		NO_ATTACHMENST,
		GET_CURRENT_WEAPON_WHEEL_HASH,
		SET_WEAPON_WHEEL_ACTIVE,
		UNLOAD_WEAPON_WHEEL_STATS,
		UNLOAD_WEAPON_WHEEL,
		SET_RETICLE_VISIBLE,
		SHOW_HITMARKER,
		SET_SATNAV_DIRECTION,
		HIDE_SATNAV,
		HIDE_DEPTH,
		SET_SATNAV_DISTANCE,
		SET_SATNAV_AREA,
		SET_DEPTH,
		SHOW_DEPTH,
		SET_BACKGROUND_COLOURS,
		DRAW_INSTRUCTIONAL_BUTTONS,
		SET_DATA_SLOT,
		SET_CLEAR_SPACE,
		DISPLAY_DATA_SLOT,
		SET_STATUS_COLOURS,
		STORE_FREE_PRICE, // maybe at the hair cut studio

		// Ui menu selector ADD_COLUMN,
		REMOVE_COLUMN,
		STORE_NO_CONTENT,

		DISPLAY_ERROR_MESSAGE,
		SET_LANGUAGES,
		SET_CONTEXT_SLOT,
		SHOW_CONTEXT_MENU,
		CONTROLLER_LABLES,
		SET_CONTROL_LABLS,
		INIT_COLUMN_SCROLL,
		UPDATE_SLOT,
		BEGI_RESTART_PAUSE_MENU,
		SET_HEADING_DETAILS,
		SET_CHAR_IMG,
		SET_CREW_IMG,
		SET_ALL_HIGHLIGHTS,
		SET_MENU_HEADER_TEXT_BY_INDEX,
		SET_MENU_ITEM_COLOUR,
		SET_DIMMABLE,
		BUILD_MENU_GFX_FILES,
		BUILD_MENU,
		SHOW_HEADIG_DETAILS,
		SET_HEADER_TITLE,
		LOAD_CHILD_PAGE,
		SET_CONTENT_SCALED,
		MENU_SHIFT_DEPTH,
		SET_TITLE,
		SET_COLUMN_HIGHLIGHT,
		SET_COLUMN_FOCUS,
		SHOW_COLUMN,
		SET_COLUMN_SCROLL,
		SHOW_WARNING_MESSAGE,
		SCROLL_POLICY_TEXT,

		// To be continued 
		// .rdata:82019224 00000026 C SET_WELCOME_FALLBACK_IMAGE_VISIBILITY
	};

	enum eVDelays {
		FEED_DELAY_1HOUR,
		FEED_DELAY_30MIN,
		FEED_DELAY_15MIN,
		FEED_DELAY_4MIN,
		FEED_DELAY_10MIN,
		FEED_DELAY_5MIN,
		FEED_DELAY_3MIN,
		FEED_DELAY_2MIN,
		FEED_DELAY_1MIN,
		FEED_NO_DELAY
	};

	enum eVPCards {
		PCARD_SEND_INVT_TITLE,
		PCARD_ONLINE_OTHER,
		PCARD_ONLINE_SP,
		PCARD_ONLINE_MP,
		PCARD_ONLINE_SES,
		PCARD_NEVER_PLAYED_SP,
		PCARD_JOIN_CREW,
		PCARD_UPDATE_SC,
		PCARD_JOIN_SC,
		PCARD_INVITE_CREW_ALT,
		PCARD_INVITE_CREW,
		PCARD_NO_CREW,
		PCARD_CREW_INVITE,
		PCARD_SYNCING_STATS,
		PCARD_NEVER_PLAYED_MP,
		PCARD_SYNC_ERROR,
		PCARD_SEND_INVT_TEXT
	};

	enum eVErrors {
		ERROR_NO_SC,
		ERROR_UPDATE_SC,
		ERROR_GAL_HDR,
		ERROR_EMPTY_,
		ERROR_EMPTY_TITLE,
		ERROR_PROFANITY_HEADER,
		ERROR_FAILEDPROFANITY,
		ERROR_DEL_HDR,
		ERROR_DELTE,
		ERROR_PROFILESETTIGNS_FACEBOOK,
		ERROR_FB_HEADER,
		ERROR_FACEBOOK,
	};

	enum eVCorona {
		CORONA_INVITE_LAST_JOB_PLAYERS,
		CORONA_INVITE_MATCHED_PLAYERS,
		CORONA_INVITE_JOINED,
		CORONA_INVITE_PLAYERS,
		CORONA_INVITE_FRIENDS,
		CORONA_INVITE_CREWS
	};

	enum eVGangs {
		GANG_YOU_DROP_WEAPON,
		GANG_WEAPON_WARNING,
		GANG_WATCH_THIS_GUY_SOLO,
		GANG_WATCH_THIS_GUY_RESP,
		GANG_WATCH_THIS_GUY,
		GANG_INTERVENE,
		GANG_FIGHT_CHEER,
		GANG_DODGE_WARNING,
		GANG_CHASE,
		GANG_BUMP,
		GANG_ATTACK_WARNING,
		GANG_ASK_PLAYER_LEAVE
	};

	enum eVPoliceScanner {
		SUSPECT_IN_CUSTODY,
		SUSPECT_DOWN,
		POLICE_SCANNER_CONJUNCTIVES_FOR,
		INSTRUCTIONS_DISPATH_TO,
		POLICE_CAR_NUMBER,
		POLICE_CAR_NAME,
		POLICE_SCANNER_RANDOM_CHAT,
		POLICE_SCANNER_A,
		POLICE_SCANNER_IN,
		POLICE_SCANNER_ON_SHORT,
		POLICE_SCANNER_ON_FOOT,
		POLICE_SCANNER_LAST_SEEN,
		POLICE_SCANNER_SUSPECT,
		POLICE_SCANNER_NEAR_DIR_PERCENTs,
		POLICE_SCANNER_CONJUNCTIVES_NEAR,
		POLICE_SCANNER_CONJUNCTIVES_AT,
		NORTH_OF_UHM,
		EAST_OF_UHM,
		SOUTH_OF_UHM,
		WEST_OF_UHM,
		POLICE_SCANNER_IN_DIRECTION,
		IN_CENTRAL,
		NORTHERN,
		EASTERN,
		SOUTHERN,
		WESTERN,
		NORTH,
		EAST,
		SOUTH,
		WEST,
		PERCENTDOT2i_SCANNER_VOICE_PARAMS,
		POLICE_SCANNER_COLOUR_FUCKED,
		CRIME_AMBIENT_MEDICAL_EVENT,
		CRIME_AMBIENT_FIRE,
		POLICE_SCANNER_ASSISTANCE_REQUIRED_ASSISTANCE_REQUIRED,
	};

	enum eVEVents {
		CEventShockingCarChase,
		CEventShockingCarCrash,
		CEventShockingBicycleCrash,
		CEventShockingCarPileUp,
		CEventShockingCarOnCar,
		CEventShockingDangerousAnimal,
		CEventShockingDeadBody,
		CEventShockingDrivingOnPavement,
		CEventShockingBicycleOnPavement,
		CEventShockingEngineRevved,
		CEventShockingExplosion,
		CEventShockingFire,
		CEventShockingGunFight,
		CEventShockingGunshotFired,
		CEventShockingHelicopterOverhead,
		CEventShockingParachuterOverhead,
		CEventShockingHornSounded,
		CEventShockingInjuredPed,
		CEventShockingInDangerousVehicle,
		CEventShockingMadDriver,
		CEventShockingMadDriverExtreme,
		CEventShockingMadDriverBicycle,
		CEventShockingMugging,
		CEventShockingPedKnockedIntoByPlayer,
		CEventShockingPedRunOver,
		CEventShockingPedShot,
		CEventShockingPlaneFlyby,
		CEventShockingPotentialBlast,
		CEventShockingPropertyDamage,
		CEventShockingRunningPed,
		CEventShockingRunningStampede,
		CEventShockingSeenCarStolen,
		CEventShockingSeenConfrontation,
		CEventShockingSeenGangFight,
		CEventShockingSeenInsult,
		CEventShockingSeenMeleeAction,
		CEventShockingSeenNiceCar,
		CEventShockingSeenPedKilled,
		CEventShockingSiren,
		CEventShockingCarAlarm,
		CEventShockingStudioBomb,
		CEventShockingVehicleTowed,
		CEventShockingWeaponThreat,
		CEventShockingVisibleWeapon,
		CEventShockingWeirdPed,
		CEventShockingWeirdPedApproaching,
		CEventShockingNonViolentWeaponAimedAt
	};

	enum eVDTs {
		DT_ArmyVehicle,
		DT_PoliceBoat,
		DT_SwatHelicopter,
		DT_Gangs,
		DT_PoliceAutomobileWaitCruising,
		DT_PoliceAutomobileWaitPulledOver,
		DT_PoliceRoadBlock,
		DT_PoliceVehicleRequest,
		DT_PoliceRiders,
		DT_AmbulanceDepartment,
		DT_SwatAutomobile,
		DT_FireDepartment,
		DT_PoliceHelicopter,
		DT_PoliceAutomobile,
		DT_Invalid
	};

	enum eVCopSees {
		COP_SEES_WEAPON,
		COP_SEES_GUN,
		COP_SEES_MINI_GUN,
		COP_SEES_GRENADE,
		COP_SEES_GRENADE_LAUNCHER,
		COP_SEES_ROCKET_LAUNCHER
	};

	enum eVEntityTypes {
		ARMY,
		ANIMAL,
		SWAT,
		MISSION,
		SPECIAL,
		PROSTITUTE,
		CRIMINAL,
		FIREMAN,
		MEDIC,
		DEALER,
		GANG_PUERTO_RICAN,
		GANG_CHINESE_JAPANESE,
		GANG_KOREAN,
		GANG_AFRICAN_AMERICAN,
		GANG_JAMAICAN,
		GANG_IRISH,
		GANG_RUSSIAN_2,
		GANG_RUSSIAN,
		GANG_ITALIAN,
		GANG_BIKER_2,
		GANG_BIKER_1,
		GANG_ALBANIAN,
		CIVFEMALE,
		PLAYER_2, // trevor(the orange one)
		NETWORK_PLAYER, // multiplayer(the yellow one)
		PLAYER_1, // franklin(the green one)
		PLAYER_0, // michael(the blue one)
	};

	enum eVCMS {
		CSM_ST_CLOUDS_DITHER2_LINEAR,
		CSM_ST_CLOUDS_BOX4x4,
		CSM_ST_CLOUDS_BOX3x3,
		CSM_ST_CLOUDS_TWOTAP,
		CSM_ST_CLOUDS_LINEAR,
		CSM_ST_CLOUDS_SIMPLE,
		CSM_ST_HIGHRES_BOX4x4,
		CSM_ST_SOFT16,
		CSM_ST_DITHER16,
		CSM_ST_DITHER4,
		CSM_ST_CUBIC,
		CSM_ST_DITHER2_LINEAR,
		CSM_ST_BOX4x4,
		CSM_ST_BOX3x3,
		CSM_ST_TWOTAP,
		CSM_ST_LINEAR,
		CSM_ST_POINT
	};

	enum eVDLs {
		DL_BEGIN_DRAW,
		DL_DEBUG,
		DL_MIRROR_REFLECTION,
		DL_RAIN_COLLISION_MAP,
		DL_RAIN_UPDATE,
		DL_PLAYER_SETTINGS,
		DL_PED_DAMAGE_GEN,
		DL_CLOUD_GEN,
		DL_HEIGHT_MAP,
		DL_PREAMBLE,
		DL_FRONTEND,
		DL_HUD,
		DL_PHONE,
		DL_SEETHROUGH_MAP,
		DL_REFLECTION_MAP,
		DL_WATER_SURFACE,
		DL_TREE,
		DL_SCRIPT,
		DL_TIMEBARS,
		DL_PRE_RENDER_VP,
		DL_RADAR,
		DL_LIGHTING
	};

	enum eVSGStates {
		SG_RPT_SAVES,
		SG_PH_SV_CL_FL,
		SG_PH_LD_CL_FL,
		SG_PH_LS_CL_FL,
		SG_DEL_C_FAIL,
		SG_DEL_FAIL,
		SG_ALD_DAM,
		SG_ALD_SIGN_AGN,
		SG_ALD_SIGNIN,
		SG_VERS_ERR,
		SG_FILENAME_DUP,
		SG_FILENAME_ERR,
		SG_TOOMANYFILES,
		SG_SAVEOVR_SURE,
		SG_SAVE_OVRWRT,
		SG_SAVE_OVRWRT2,
		SG_LOAD_OVRWRT,
		SG_AUTO_OFF,
		SG_AUTOOFF_SURE,
		SG_AUTO_FAILED,
		SG_AUTO_SL_OVR,
		SG_AUTO_SL_OVR2,
		SG_DEV_REM,
		SG_CHKLOAD_FAIL,
		SG_BUFFSIZE_DIF,
		SG_NOT_CREATOR,
		SG_BGNLOAD_FAIL,
		SG_CHKTIME_FAIL,
		SG_BGNTIME_FAIL,
		SG_CHKSAVE_FAIL,
		SG_ENUM_FAILED,
		SG_DEL_LST_FAIL,
		SG_SPCHK_FAILED,
		SG_DEV_SEL_FAIL,
		SG_NO_SPCE_360,
		SG_SPACE_360,
		SG_SEL_DEV_AGN,
		SG_DEVICE_REM,
		SG_DEV_REM_AUTO,
		SG_SGN_SV_RPT_A,
		SG_SIGNIN_AGN,
		SG_SIGNIN_ATSV,
		SG_SGN_SV_RPT,
		SG_SIGNIN_SV,
		SG_SIGNIN
	};

	enum eVBasicPedTasks {
		GC_COMBAT_TASK,
		GC_LOCAL_PLAYER,
		GC_SITTING,
		GC_WALKING,
		GC_VEHICLE_PASSENGER,
		GC_VEHICLE_DRIVER,
		GC_OBJECT_RIGHT_HAND,
		GC_OBJECT_LEFT_HAND,
		GC_CONVERSATION_HANGOUT, GC_CONVERSATION_PHONE,
		GC_DEFAULT
	};

	enum eVInputGroups {
		INPUTGROUP_VEH_MOVE_ALL,
		INPUTGROUP_SUB,
		INPUTGROUP_FLY,
		INPUTGROUP_WEAPON_WHEEL_CYCLE,
		INPUTGROUP_SCRIPT_RSTICK_ALL,
		INPUTGROUP_SCRIPT_LSTICK_ALL,
		INPUTGROUP_SCRIPT_DPAD_LR,
		INPUTGROUP_SCRIPT_DPAD_UD,
		INPUTGROUP_SCRIPT_DPAD_ALL,
		INPUTGROUP_FRONTEND_GENERIC_ALL,
		INPUTGROUP_FRONTEND_GENERIC_LR,
		INPUTGROUP_FRONTEND_GENERIC_UD,
		INPUTGROUP_FRONTEND_RSTICK_ALL,
		INPUTGROUP_FRONTEND_LSTICK_ALL,
		INPUTGROUP_FRONTEND_DPAD_LR,
		INPUTGROUP_FRONTEND_DPAD_UD,
		INPUTGROUP_FRONTEND_DPAD_ALL,
		INPUTGROUP_CELLPHONE_NAVIGATE_LR,
		INPUTGROUP_CELLPHONE_NAVIGATE_UD,
		INPUTGROUP_CELLPHONE_NAVIGATE,
		INPUTGROUP_WHEEL,
		INPUTGROUP_LOOK,
		INPUTGROUP_MOVE
	};

	enum eVInputs {
		INPUT_REPLAY_PREVIEW,
		INPUT_REPLAY_TOGGLETIPS,
		INPUT_REPLAY_TOGGLETIME,
		INPUT_REPLAY_SAVE,
		INPUT_REPLAY_CAMERADOWN,
		INPUT_REPLAY_CAMERAUP,
		INPUT_REPLAY_FOVDECREASE,
		INPUT_REPLAY_FOVINCREASE,
		INPUT_REPLAY_CYCLEMARKERRIGHT,
		INPUT_REPLAY_CYCLEMARKERLEFT,
		INPUT_REPLAY_SHOWHOTKEY,
		INPUT_REPLAY_RESTART,
		INPUT_REPLAY_TOOLS,
		INPUT_REPLAY_BACK,
		INPUT_REPLAY_ADVANCE,
		INPUT_REPLAY_ENDPOINT,
		INPUT_REPLAY_STARTPOINT,
		INPUT_REPLAY_HIDEHUD,
		INPUT_REPLAY_SCREENSHOT,
		INPUT_REPLAY_RECORD,
		INPUT_REPLAY_NEWMARKER,
		INPUT_REPLAY_FFWD,
		INPUT_REPLAY_REWIND,
		INPUT_REPLAY_PAUSE,
		INPUT_REPLAY_MARKER_DELETE,
		INPUT_VEH_LOOK_RIGHT,
		INPUT_VEH_LOOK_LEFT,
		INPUT_VEH_GUN_DOWN,
		INPUT_VEH_GUN_UP,
		INPUT_VEH_GUN_RIGHT,
		INPUT_VEH_GUN_LEFT,
		INPUT_VEH_MOVE_DOWN,
		INPUT_VEH_MOVE_UP,
		INPUT_VEH_MOVE_RIGHT,
		INPUT_VEH_MOVE_LEFT,
		INPUT_VEH_HANDBRAKE_ALT,
		INPUT_SNIPER_ZOOM_OUT_ALTERNATE,
		INPUT_SNIPER_ZOOM_IN_ALTERNATE,
		INPUT_SNIPER_ZOOM_OUT,
		INPUT_SNIPER_ZOOM_IN,
		INPUT_LOOK_DOWN,
		INPUT_LOOK_UP,
		INPUT_LOOK_RIGHT,
		INPUT_LOOK_LEFT,
		INPUT_MOVE_DOWN,
		INPUT_MOVE_UP,
		INPUT_MOVE_RIGHT,
		INPUT_MOVE_LEFT,
		INPUT_WHISTLE,
		INPUT_MELEE_ATTACK2,
		INPUT_MELEE_ATTACK1,
		INPUT_NEXT_WEAPON,
		INPUT_PREV_WEAPON,
		INPUT_RAPPEL_SMASH_WINDOW,
		INPUT_RAPPEL_LONG_JUMP,
		INPUT_RAPPEL_JUMP,
		INPUT_ATTACK2,
		INPUT_SCRIPT_SELECT,
		INPUT_SCRIPT_PAD_RIGHT,
		INPUT_SCRIPT_PAD_LEFT,
		INPUT_SCRIPT_PAD_DOWN,
		INPUT_SCRIPT_PAD_UP,
		INPUT_SCRIPT_RS,
		INPUT_SCRIPT_LS,
		INPUT_SCRIPT_RT,
		INPUT_SCRIPT_LT,
		INPUT_SCRIPT_RB,
		INPUT_SCRIPT_LB,
		INPUT_SCRIPT_RRIGHT,
		INPUT_SCRIPT_RLEFT,
		INPUT_SCRIPT_RDOWN,
		INPUT_SCRIPT_RUP,
		INPUT_SCRIPT_RIGHT_AXIS_Y,
		INPUT_SCRIPT_RIGHT_AXIS_X,
		INPUT_SCRIPT_LEFT_AXIS_Y,
		INPUT_SCRIPT_LEFT_AXIS_X,
		INPUT_FRONTEND_SELECT,
		INPUT_FRONTEND_RS,
		INPUT_FRONTEND_LS,
		INPUT_FRONTEND_RT,
		INPUT_FRONTEND_LT,
		INPUT_FRONTEND_RB,
		INPUT_FRONTEND_LB,
		INPUT_FRONTEND_Y,
		INPUT_FRONTEND_X,
		INPUT_FRONTEND_CANCEL,
		INPUT_FRONTEND_ACCEPT,
		INPUT_FRONTEND_PAUSE,
		INPUT_FRONTEND_RIGHT_AXIS_Y,
		INPUT_FRONTEND_RIGHT_AXIS_X,
		INPUT_FRONTEND_AXIS_Y,
		INPUT_FRONTEND_AXIS_X,
		INPUT_FRONTEND_RRIGHT,
		INPUT_FRONTEND_RLEFT,
		INPUT_FRONTEND_RUP,
		INPUT_FRONTEND_RDOWN,
		INPUT_FRONTEND_RIGHT,
		INPUT_FRONTEND_LEFT,
		INPUT_FRONTEND_UP,
		INPUT_FRONTEND_DOWN,
		INPUT_CELLPHONE_SCROLL_BACKWARD,
		INPUT_CELLPHONE_SCROLL_FORWARD,
		INPUT_CELLPHONE_EXTRA_OPTION,
		INPUT_CELLPHONE_OPTION,
		INPUT_CELLPHONE_CANCEL,
		INPUT_CELLPHONE_SELECT,
		INPUT_CELLPHONE_RIGHT,
		INPUT_CELLPHONE_LEFT,
		INPUT_CELLPHONE_DOWN,
		INPUT_CELLPHONE_UP,
		INPUT_SPECIAL_ABILITY_PC,
		INPUT_SAVE_REPLAY_CLIP,
		INPUT_SELECT_CHARACTER_MULTIPLAYER, INPUT_SELECT_CHARACTER_TREVOR,
		INPUT_SELECT_CHARACTER_FRANKLIN,
		INPUT_SELECT_CHARACTER_MICHAEL,
		INPUT_SELECT_WEAPON_SPECIAL,
		INPUT_SELECT_WEAPON_HEAVY,
		INPUT_SELECT_WEAPON_SNIPER,
		INPUT_SELECT_WEAPON_AUTO_RIFLE,
		INPUT_SELECT_WEAPON_SMG,
		INPUT_SELECT_WEAPON_SHOTGUN,
		INPUT_SELECT_WEAPON_HANDGUN,
		INPUT_SELECT_WEAPON_MELEE,
		INPUT_SELECT_WEAPON_UNARMED,
		INPUT_MAP,
		INPUT_PARACHUTE_SMOKE,
		INPUT_PARACHUTE_BRAKE_RIGHT,
		INPUT_PARACHUTE_BRAKE_LEFT,
		INPUT_PARACHUTE_PITCH_DOWN_ONLY,
		INPUT_PARACHUTE_PITCH_UP_ONLY,
		INPUT_PARACHUTE_PITCH_UD,
		INPUT_PARACHUTE_TURN_RIGHT_ONLY,
		INPUT_PARACHUTE_TURN_LEFT_ONLY,
		INPUT_PARACHUTE_TURN_LR,
		INPUT_PARACHUTE_DETACH,
		INPUT_PARACHUTE_DEPLOY,
		INPUT_MELEE_BLOCK,
		INPUT_MELEE_ATTACK_ALTERNATE,
		INPUT_MELEE_ATTACK_HEAVY,
		INPUT_MELEE_ATTACK_LIGHT,
		INPUT_VEH_SUB_TURN_HARD_RIGHT,
		INPUT_VEH_SUB_TURN_HARD_LEFT,
		INPUT_VEH_SUB_DESCEND,
		INPUT_VEH_SUB_ASCEND,
		INPUT_VEH_SUB_THROTTLE_DOWN,
		INPUT_VEH_SUB_THROTTLE_UP,
		INPUT_VEH_SUB_PITCH_DOWN_ONLY,
		INPUT_VEH_SUB_PITCH_UP_ONLY,
		INPUT_VEH_SUB_PITCH_UD,
		INPUT_VEH_SUB_TURN_RIGHT_ONLY,
		INPUT_VEH_SUB_TURN_LEFT_ONLY,
		INPUT_VEH_SUB_TURN_LR,
		INPUT_VEH_FLY_VERTICAL_FLIGHT_MODE, INPUT_VEH_FLY_SELECT_TARGET_RIGHT,
		INPUT_VEH_FLY_SELECT_TARGET_LEFT,
		INPUT_VEH_FLY_SELECT_PREV_WEAPON,
		INPUT_VEH_FLY_SELECT_NEXT_WEAPON,
		INPUT_VEH_FLY_ATTACK,
		INPUT_VEH_FLY_UNDERCARRIAGE,
		INPUT_VEH_FLY_PITCH_DOWN_ONLY,
		INPUT_VEH_FLY_PITCH_UP_ONLY,
		INPUT_VEH_FLY_PITCH_UD,
		INPUT_VEH_FLY_ROLL_RIGHT_ONLY,
		INPUT_VEH_FLY_ROLL_LEFT_ONLY,
		INPUT_VEH_FLY_ROLL_LR,
		INPUT_VEH_GRAPPLING_HOOK,
		INPUT_VEH_JUMP,
		INPUT_VEH_ROOF,
		INPUT_VEH_SELECT_PREV_WEAPON,
		INPUT_VEH_SELECT_NEXT_WEAPON,
		INPUT_VEH_CINEMATIC_LR,
		INPUT_VEH_CINEMATIC_DOWN_ONLY,
		INPUT_VEH_CINEMATIC_UP_ONLY,
		INPUT_VEH_CINEMATIC_UD,
		INPUT_VEH_STUNT_UD,
		INPUT_VEH_SPECIAL_ABILITY_FRANKLIN, INPUT_VEH_PASSENGER_ATTACK,
		INPUT_VEH_PASSENGER_AIM,
		INPUT_VEH_FLY_YAW_RIGHT,
		INPUT_VEH_FLY_YAW_LEFT,
		INPUT_VEH_FLY_THROTTLE_DOWN,
		INPUT_VEH_FLY_THROTTLE_UP,
		INPUT_VEH_HORN,
		INPUT_VEH_RADIO_WHEEL,
		INPUT_VEH_PREV_RADIO,
		INPUT_VEH_NEXT_RADIO,
		INPUT_VEH_CIN_CAM,
		INPUT_VEH_LOOK_BEHIND,
		INPUT_VEH_HOTWIRE_RIGHT,
		INPUT_VEH_HOTWIRE_LEFT,
		INPUT_VEH_HANDBRAKE,
		INPUT_VEH_EXIT,
		INPUT_VEH_HEADLIGHT,
		INPUT_VEH_BRAKE,
		INPUT_VEH_ACCELERATE,
		INPUT_VEH_ATTACK2,
		INPUT_VEH_ATTACK,
		INPUT_VEH_AIM,
		INPUT_VEH_GUN_UD,
		INPUT_VEH_GUN_LR,
		INPUT_VEH_SPECIAL,
		INPUT_VEH_MOVE_RIGHT_ONLY,
		INPUT_VEH_MOVE_LEFT_ONLY,
		INPUT_VEH_MOVE_DOWN_ONLY,
		INPUT_VEH_MOVE_UP_ONLY,
		INPUT_VEH_MOVE_UD,
		INPUT_VEH_MOVE_LR,
		INPUT_DIVE,
		INPUT_WEAPON_SPECIAL_TWO,
		INPUT_WEAPON_SPECIAL,
		INPUT_CONTEXT,
		INPUT_ACCURATE_AIM,
		INPUT_ARREST,
		INPUT_HUD_SPECIAL,
		INPUT_DETONATE,
		INPUT_TALK,
		INPUT_RELOAD,
		INPUT_COVER,
		INPUT_SNIPER_ZOOM_OUT_ONLY,
		INPUT_SNIPER_ZOOM_IN_ONLY,
		INPUT_SNIPER_ZOOM,
		INPUT_PICKUP,
		INPUT_SELECT_WEAPON,
		INPUT_DUCK,
		INPUT_MOVE_RIGHT_ONLY,
		INPUT_MOVE_LEFT_ONLY,
		INPUT_MOVE_DOWN_ONLY,
		INPUT_MOVE_UP_ONLY,
		INPUT_MOVE_UD,
		INPUT_MOVE_LR,
		INPUT_SPECIAL_ABILITY_SECONDARY,
		INPUT_SPECIAL_ABILITY,
		INPUT_PHONE,
		INPUT_LOOK_BEHIND,
		INPUT_AIM,
		INPUT_ATTACK,
		INPUT_ENTER,
		INPUT_JUMP,
		INPUT_SPRINT,
		INPUT_MULTIPLAYER_INFO,
		INPUT_CHARACTER_WHEEL,
		INPUT_SKIP_CUTSCENE,
		INPUT_SELECT_PREV_WEAPON,
		INPUT_SELECT_NEXT_WEAPON,
		INPUT_WEAPON_WHEEL_PREV,
		INPUT_WEAPON_WHEEL_NEXT,
		INPUT_WEAPON_WHEEL_LR,
		INPUT_WEAPON_WHEEL_UD,
		INPUT_SCRIPTED_FLY_ZDOWN,
		INPUT_SCRIPTED_FLY_ZUP,
		INPUT_SCRIPTED_FLY_LR,
		INPUT_SCRIPTED_FLY_UD,
		INPUT_CINEMATIC_SLOWMO,
		INPUT_LOOK_RIGHT_ONLY,
		INPUT_LOOK_LEFT_ONLY,
		INPUT_LOOK_DOWN_ONLY,
		INPUT_LOOK_UP_ONLY,
		INPUT_LOOK_UD,
		INPUT_LOOK_LR,
		INPUT_NEXT_CAMERA
	};

	enum eVGameEvents {
		START_PROJECTILE_EVENT,
		SET_LOOK_AT_ENTITY,
		SET_TASK_VEHICLE_TEMP_ACTION,
		REQUEST_CONTROL_EVENT,
		GIVE_CONTROL_EVENT,
		WEAPON_DAMAGE_EVENT,
		REQUEST_PICKUP_EVENT,
		GAME_CLOCK_EVENT,
		GAME_WEATHER_EVENT,
		RESPAWN_PLAYER_PED_EVENT,
		GIVE_WEAPON_EVENT,
		REMOVE_WEAPON_EVENT,
		REMOVE_ALL_WEAPONS_EVENT,
		VEHICLE_COMPONENT_CONTROL_EVENT,
		REQUEST_FIRE_EVENT,
		CONFIRM_FIRE_EVENT,
		ALTER_WANTED_LEVEL_EVENT,
		CHANGE_RADIO_STATION_EVENT,
		RAGDOLL_REQUEST_EVENT,
		PLAYER_TAUNT_EVENT,
		PLAYER_CARD_STAT_EVENT,
		PED_CONVERSATION_LINE_EVENT,
		DOOR_BREAK_EVENT, SCRIPTED_GAME_EVENT,
		REMOTE_SCRIPT_LEAVE_EVENT,
		MARK_AS_NO_LONGER_NEEDED_EVENT,
		SCRIPT_WORLD_STATE_EVENT,
		INCIDENT_ENTITY_EVENT,
		CLEAR_AREA_EVENT,
		REQUEST_NETWORK_SYNCED_SCENE_EVENT,
		START_NETWORK_SYNCED_SCENE_EVENT,
		STOP_NETWORK_SYNCED_SCENE_EVENT,
		UPDATE_NETWORK_SYNCED_SCENE_EVENT,
		GIVE_PED_SCRIPTED_TASK_EVENT,
		CLEAR_PED_TASKS_EVENT,
		START_NETWORK_PED_ARREST_EVENT,
		START_NETWORK_PED_UNCUFF_EVENT,
		NETWORK_CAR_HORN_EVENT,
		NETWORK_ENTITY_AREA_STATUS_EVENT,
		NETWORK_GARAGE_OCCUPIED_STATUS_EVENT,
		SCRIPT_ENTITY_STATE_CHANGE_EVENT,
		PLAY_SOUND_EVENT,
		STOP_SOUND_EVENT,
		BANK_REQUEST_EVENT,
		REQUEST_DOOR_EVENT,
		NETWORK_TRAIN_REQUEST_EVENT,
		NETWORK_TRAIN_REPORT_EVENT,
		MODIFY_VEHICLE_LOCK_WORLD_STATE_DATA_EVENT,
		NETWORK_INCREMENT_STAT_EVENT,
		REQUEST_PHONE_EXPLOSION_EVENT,
		REQUEST_RADIO_STATION_DATA_EVENT,
		KICK_VOTES_EVENT,
		NETWORK_GIVE_PICKUP_REWARD_EVENT,
		NETWORK_CRC_HASH_CHECK_EVENT,
		BLOW_UP_VEHICLE_EVENT,
		NETWORK_SPECIAL_FIRE_EQUIPPED_WEAPON,
		NETWORK_RESPONDED_TO_THREAD_EVENT,
		DESTROYING_EVENT,
		REMOTE_SCRIPT_INFO_EVENT,
		CONVERT_TO_SCRIPT_ENTITY_EVENT,
		SCRIPT_DATA_VERIFY_EVENT,
		REQUEST_MAP_PICKUP_EVENT,
		GIVE_PED_SEQUENCE_TASK_EVENT,
		EXPLOSION_EVENT,
		GIVE_PICKUP_REWARDS_EVENT,
		MODIFY_VEHICLE_LOCK_WORD_STATE_DATA_EVENT,
		NETWORK_BANK_REQUEST_EVENT,
		NETWORK_STOP_SOUND_EVENT,
		NETWORK_PLAY_SOUND_EVENT,
		NETWORK_SOUND_CAR_HORN_EVENT,
		NETWORK_START_PED_UNCUFF_EVENT,
		NETWORK_START_PED_ARREST_EVENT,
		NETWORK_CLEAR_PED_TASKS_EVENT,
		NETWORK_STOP_SYNCED_SCENE_EVENT,
		NETWORK_UPDATE_SYNCED_SCENE_EVENT,
		NETWORK_START_SYNCED_SCENE_EVENT,
		NETWORK_REQUEST_SYNCED_SCENE_EVENT,
		WEATHER_EVENT,
		CLOCK_EVENT,
		SCRIPT_ARRAY_DATA_VERIFY_EVENT
	};

	enum eVSupportedFormats {
		GSM,
		SD2,
		MPG4,
		MP4,
		MP2,
		MPEG,
		VFW,
		AVI,
		MOV,
		MP3,
		ULW,
		SND,
		AIFC,
		AIFF,
		AIF,
		WAV,
		BIK
	};

	enum eVThreads {
		THREAD_VOICECHAT_WORKER, // [RAGE] VoiceChat Worker
		THREAD_NETPOOL_1, // [RAGE] netThreadPool 1
		THREAD_NETPOOL_2, // [RAGE] netThreadPool 2
		THREAD_NETTCP_WORKER, // [RAGE] netTcp Worker 
		THREAD_ACHIEVEMENT_WORKER, // [RAGE] rlAchievement Worker 
		THREAD_RENDERTHREAD, // [RAGE] RenderThread 
		THREAD_DVDREADER, // [RAGE] DVD Reader 
		THREAD_HDDREADER, // [RAGE] HDD Reader 
		THREAD_DVDSTREAMER, // [RAGE] DVD Streamer 
		THREAD_HDDSTREAMER // [RAGE] HDD Streamer
	};

	enum eVSupportedPCInputs {
		IOMS_FORCE32,
		IOMS_MKB_AXIS,
		IOMS_DIGITALBUTTON_AXIS,
		IOMS_PAD_DEBUGBUTTON,
		IOMS_JOYSTICK_POV_AXIS,
		IOMS_JOYSTICK_POV,
		IOMS_JOYSTICK_AXIS_POSITIVE,
		IOMS_JOYSTICK_AXIS_NEGATIVE,
		IOMS_JOYSTICK_IAXIS,
		IOMS_JOYSTICK_AXIS,
		IOMS_JOYSTICK_BUTTON,
		IOMS_PAD_AXIS,
		IOMS_PAD_ANALOGBUTTON,
		IOMS_PAD_DIGITALBUTTONANY,
		IOMS_PAD_DIGITALBUTTON,
		IOMS_MOUSE_BUTTONANY,
		IOMS_MOUSE_BUTTON,
		IOMS_MOUSE_WHEEL,
		IOMS_MOUSE_SCALEDAXIS,
		IOMS_MOUSE_RELATIVEAXIS,
		IOMS_MOUSE_CENTEREDAXIS,
		IOMS_MOUSE_ABSOLUTEAXIS,
		IOMS_KEYBOARD,
		IOMS_UNDEFINED,
		IOM_POV4_LEFT,
		IOM_POV4_DOWN,
		IOM_POV4_RIGHT,
		IOM_POV4_UP,
		IOM_POV3_LEFT,
		IOM_POV3_DOWN,
		IOM_POV3_RIGHT,
		IOM_POV3_UP,
		IOM_POV2_LEFT,
		IOM_POV2_DOWN,
		IOM_POV2_RIGHT,
		IOM_POV2_UP,
		IOM_POV1_LEFT,
		IOM_POV1_DOWN,
		IOM_POV1_RIGHT,
		IOM_POV1_UP,
		IOM_JOYSTICK_AXIS8,
		IOM_JOYSTICK_AXIS7,
		IOM_JOYSTICK_AXIS6,
		IOM_JOYSTICK_AXIS5,
		IOM_JOYSTICK_AXIS4,
		IOM_JOYSTICK_AXIS3,
		IOM_JOYSTICK_AXIS2,
		IOM_JOYSTICK_AXIS1,
		IOM_JOYSTICK_BUTTON32,
		IOM_JOYSTICK_BUTTON31,
		IOM_JOYSTICK_BUTTON30,
		IOM_JOYSTICK_BUTTON29,
		IOM_JOYSTICK_BUTTON28,
		IOM_JOYSTICK_BUTTON27,
		IOM_JOYSTICK_BUTTON26,
		IOM_JOYSTICK_BUTTON25,
		IOM_JOYSTICK_BUTTON24,
		IOM_JOYSTICK_BUTTON23,
		IOM_JOYSTICK_BUTTON22,
		IOM_JOYSTICK_BUTTON21,
		IOM_JOYSTICK_BUTTON20,
		IOM_JOYSTICK_BUTTON19,
		IOM_JOYSTICK_BUTTON18,
		IOM_JOYSTICK_BUTTON17,
		IOM_JOYSTICK_BUTTON16,
		IOM_JOYSTICK_BUTTON15,
		IOM_JOYSTICK_BUTTON14,
		IOM_JOYSTICK_BUTTON13,
		IOM_JOYSTICK_BUTTON12,
		IOM_JOYSTICK_BUTTON11,
		IOM_JOYSTICK_BUTTON10,
		IOM_JOYSTICK_BUTTON9,
		IOM_JOYSTICK_BUTTON8,
		IOM_JOYSTICK_BUTTON7,
		IOM_JOYSTICK_BUTTON6,
		IOM_JOYSTICK_BUTTON5,
		IOM_JOYSTICK_BUTTON4,
		IOM_JOYSTICK_BUTTON3,
		IOM_JOYSTICK_BUTTON2,
		IOM_JOYSTICK_BUTTON1,
		IOM_AXIS_RX_RIGHT,
		IOM_AXIS_RX_LEFT,
		IOM_AXIS_RY_DOWN,
		IOM_AXIS_RY_UP,
		IOM_AXIS_LX_RIGHT,
		IOM_AXIS_LX_LEFT,
		IOM_AXIS_LY_DOWN,
		IOM_AXIS_LY_UP,
		IOM_AXIS_DPADY,
		IOM_AXIS_DPADX,
		IOM_AXIS_RDL,
		IOM_AXIS_RDR,
		IOM_AXIS_RUL,
		IOM_AXIS_RUR,
		IOM_AXIS_RRIGHT,
		IOM_AXIS_RLEFT,
		IOM_AXIS_RDOWN,
		IOM_AXIS_RUP,
		IOM_AXIS_LDL,
		IOM_AXIS_LDR,
		IOM_AXIS_LUL,
		IOM_AXIS_LUR,
		IOM_AXIS_LRIGHT,
		IOM_AXIS_LLEFT,
		IOM_AXIS_LDOWN,
		IOM_AXIS_LUP,
		IOM_AXIS_RY,
		IOM_AXIS_RX,
		IOM_AXIS_LY,
		IOM_AXIS_LX,
		NUMBUTTONS,
		TOUCH_INDEX,
		LLEFT_INDEX,
		LDOWN_INDEX,
		LRIGHT_INDEX,
		LUP_INDEX,
		START_INDEX,
		R3_INDEX,
		L3_INDEX,
		SELECT_INDEX,
		RLEFT_INDEX,
		RDOWN_INDEX,
		RRIGHT_INDEX,
		RUP_INDEX,
		R1_INDEX,
		L1_INDEX,
		R2_INDEX,
		L2_INDEX,
		TOUCH,
		LLEFT,
		LDOWN,
		LRIGHT,
		RLEFT,
		RDOWN,
		RRIGHT,
		MOUSE_EXTRABTN5,
		MOUSE_EXTRABTN,
		MOUSE_EXTRABTN3,
		MOUSE_EXTRABTN2,
		MOUSE_EXTRABTN1,
		MOUSE_MIDDLE,
		MOUSE_RIGHT,
		MOUSE_LEFT,
		IOM_IAXIS_WHEEL_RELATIVE,
		IOM_AXIS_WHEEL_RELATIVE,
		IOM_IAXIS_WHEEL,
		IOM_AXIS_WHEEL,
		IOM_IAXIS_WHEEL_DELTA,
		IOM_AXIS_WHEEL_DELTA,
		IOM_WHEEL_DOWN,
		IOM_WHEEL_UP,
		MOUSE_AXIS_MAX,
		IOM_AXIS_Y_DOWN,
		IOM_AXIS_Y_UP,
		IOM_AXIS_X_RIGHT,
		IOM_AXIS_X_LEFT,
		BASIC_MOUSE_AXIS_MAX,
		IOM_AXIS_Y,
		IOM_AXIS_X,
		IOM_ANY_BUTTON,
		IOM_POV_UNDEFINED,
		IOM_WHEEL_UNDEFINED,
		IOM_UNDEFINED,
		IOM_AXIS_UNDEFINED,
		KEY_CHATPAD_ORANGE_SHIFT,
		KEY_CHATPAD_GREEN_SHIFT,
		KEY_NUMPADENTER,
		KEY_PACKET,
		KEY_ICO_CLEAR,
		KEY_PROCESSKEY,
		KEY_ICO_00,
		KEY_ICO_HELP,
		KEY_OEM_102,
		KEY_AX,
		KEY_OEM_8,
		KEY_GRAVE,
		KEY_OEM_7,
		KEY_APOSTROPHE,
		KEY_OEM_6,
		KEY_RBRACKET,
		KEY_OEM_5,
		KEY_BACKSLASH,
		KEY_OEM_4,
		KEY_LBRACKET,
		KEY_OEM_3,
		KEY_TILDE,
		KEY_OEM_2,
		KEY_SLASH,
		KEY_PERIOD,
		KEY_MINUS,
		KEY_COMMA,
		KEY_EQUALS,
		KEY_PLUS,
		KEY_OEM_1,
		KEY_SEMICOLON,
		KEY_LAUNCHAPP2,
		KEY_LAUNCHAPP1,
		KEY_MEDIASELECT,
		KEY_MAIL,
		KEY_PLAYPAUSE,
		KEY_MEDIASTOP,
		KEY_PREVTRACK,
		KEY_NEXTTRACK,
		KEY_VOLUMEUP,
		KEY_VOLUMEDOWN,
		KEY_MUTE,
		KEY_WEBHOME,
		KEY_WEBFAVORITES,
		KEY_WEBSEARCH,
		KEY_WEBSTOP,
		KEY_WEBREFRESH,
		KEY_WEBFORWARD,
		KEY_WEBBACK,
		KEY_RMENU,
		KEY_LMENU,
		KEY_RCONTROL,
		KEY_LCONTROL,
		KEY_RSHIFT,
		KEY_LSHIFT,
		key_FJ_ROYA,
		key_FJ_LOYA,
		key_FJ_TOUROKU,
		key_FJ_MASSHOU,
		key_FJ_JISHO,
		KEY_NUMPADEQUALS,
		KEY_SCROLL,
		KEY_NUMLOCK,
		KEY_F24,
		KEY_F23,
		KEY_F22,
		KEY_F21,
		KEY_F20,
		KEY_F19,
		KEY_F18,
		KEY_F17,
		KEY_F16,
		KEY_F15,
		KEY_F14,
		KEY_F13,
		KEY_F12,
		KEY_F11,
		KEY_F10,
		KEY_F9,
		KEY_F8,
		KEY_F7,
		KEY_F6,
		KEY_F5,
		KEY_F4,
		KEY_F3,
		KEY_F2,
		KEY_F1,
		KEY_DIVIDE,
		KEY_DECIMAL,
		KEY_SUBTRACT,
		KEY_SEPARATOR,
		KEY_ADD,
		KEY_MULTIPLY,
		KEY_NUMPAD9,
		KEY_NUMPAD8,
		KEY_NUMPAD7,
		KEY_NUMPAD6,
		KEY_NUMPAD5,
		KEY_NUMPAD4,
		KEY_NUMPAD3,
		KEY_NUMPAD2,
		KEY_NUMPAD1,
		KEY_NUMPAD0,
		KEY_SLEEP,
		KEY_APPS,
		KEY_RWIN,
		KEY_LWIN,
		KEY_Z,
		KEY_Y,
		KEY_X,
		KEY_W,
		KEY_V,
		KEY_U,
		KEY_T,
		KEY_S,
		KEY_R,
		KEY_Q,
		KEY_P,
		KEY_O,
		KEY_N,
		KEY_M,
		KEY_L,
		KEY_K,
		KEY_J,
		KEY_I,
		KEY_H,
		KEY_G,
		KEY_F,
		KEY_E,
		KEY_D,
		KEY_C,
		KEY_B,
		KEY_A,
		KEY_9,
		KEY_8,
		KEY_7,
		KEY_6,
		KEY_5,
		KEY_4,
		KEY_3,
		KEY_2,
		KEY_1,
		KEY_0,
		KEY_HELP,
		KEY_DELETE,
		KEY_INSERT,
		KEY_SNAPSHOT,
		KEY_EXE,
		KEY_SYSRQ,
		KEY_PRINT,
		KEY_SELECT,
		KEY_DOWN,
		KEY_RIGHT,
		KEY_UP,
		KEY_LEFT,
		KEY_HOME,
		KEY_END,
		KEY_NEXT,
		KEY_PAGEDOWN,
		KEY_PRIOR,
		KEY_PAGEUP,
		KEY_SPACE,
		KEY_MODECHANGE,
		KEY_ACCEPT,
		KEY_NOCONVERT,
		KEY_CONVERT,
		KEY_ESCAPE,
		KEY_KANJI,
		KEY_FINAL,
		KEY_JUNJA,
		KEY_KANA,
		KEY_CAPITAL,
		KEY_PAUSE,
		KEY_RETURN,
		KEY_CLEAR,
		KEY_TAB,
		KEY_BACK
	};

	enum eVTasks {
		TASK_TOGGLE_DUCK = 0,
		TASK_PAUSE,
		TASK_STAND_STILL,
		TASK_COWER,
		TASK_ACHIEVE_HEADING,
		TASK_FOLLOW_POINT_ROUTE,
		TASK_WANDER_STANDARD,
		TASK_TURN_PED_TO_FACE_COORD,
		TASK_CLIMB_LADDER,
		TASK_GUARD_SPHERE_DEFENSIVE_AREA,
		TASK_STAND_GUARD,
		TASK_SWAP_WEAPON,
		TASK_PARACHUTE,
		TASK_PARACHUTE_TO_TARGET,
		TASK_RAPPEL_FROM_HELI,
		TASK_PATROL,
		TASK_STAY_IN_COVER,
		TASK_SET_BLOCKING_OF_NON_TEMPORARY_EVENTS,
		TASK_FOLLOW_WAYPOINT_RECORDING,
		TASK_JUMP,
		TASK_GO_STRAIGHT_TO_COORD,
		TASK_WANDER_IN_AREA,
		TASK_COMBAT_HATED_PED_IN_AREA,
		TASK_COMBAT_HATED_TARGETS_AROUND_PED,
		TASK_COMBAT_HATED_TARGETS_AROUND_PED_TIMED,
		TASK_PERFORM_SEQUENCE,
		TASK_CLIMB,
		TASK_PERFORM_SEQUENCE_FROM_PROGRESS,
		TASK_PED_SLIDE_TO_COORD_HDG_RATE,
		TASK_START_SCENARIO_IN_PLACE,
		TASK_START_SCENARIO_AT_POSITION,
		TASK_SKY_DIVE,
		TASK_HANDS_UP,
		TASK_OPEN_VEHICLE_DOOR,
		TASK_ENTER_VEHICLE,
		TASK_LEAVE_VEHICLE,
		TASK_VEHICLE_DRIVE_TO_COORD,
		TASK_VEHICLE_DRIVE_WANDER,
		TASK_GO_STRAIGHT_TO_COORD_RELATIVE_TO_ENTITY,
		TASK_FOLLOW_TO_OFFSET_OF_ENTITY,
		TASK_SMART_FLEE_POINT,
		TASK_SMART_FLEE_PED,
		TASK_REACT_AND_FLEE_PED,
		TASK_SHOCKING_EVENT_REACT,
		TASK_COMBAT_PED,
		TASK_COMBAT_TIMED,
		TASK_FOLLOW_NAVMESH_TO_COORD,
		TASK_FOLLOW_NAVMESH_TO_COORD_ADVANCED,
		TASK_GO_TO_COORD_ANY_MEANS,
		TASK_PLAY_ANIM,
		TASK_SCRIPTED_ANIMATION,
		TASK_SYNCHRONIZED_SCENE,
		TASK_LEAVE_ANY_VEHICLE,
		TASK_TURN_PED_TO_FACE_ENTITY,
		TASK_SHUFFLE_TO_NEXT_VEHICLE_SEAT,
		TASK_EVERYONE_LEAVE_VEHICLE,
		TASK_GO_TO_COORD_WHILE_AIMING_AT_COORD,
		TASK_GO_TO_COORD_WHILE_AIMING_AT_ENTITY,
		TASK_GO_TO_COORD_AND_AIM_AT_HATED_ENTITIES_NEAR_COORD,
		TASK_GO_TO_ENTITY_WHILE_AIMING_AT_COORD,
		TASK_GO_TO_ENTITY_WHILE_AIMING_AT_ENTITY,
		TASK_VEHICLE_TEMP_ACTION,
		TASK_VEHICLE_MISSION,
		TASK_VEHICLE_MISSION_PED_TARGET,
		TASK_HELI_MISSION,
		TASK_PLANE_MISSION,
		TASK_BOAT_MISSION,
		TASK_STEALTH_KILL,
		TASK_PLANT_BOMB,
		TASK_PLANE_CHASE,
		TASK_HELI_CHASE,
		TASK_DRIVE_BY,
		TASK_USE_MOBILE_PHONE_TIMED,
		TASK_CHAT_TO_PED,
		TASK_WARP_PED_INTO_VEHICLE,
		TASK_GOTO_ENTITY_AIMING,
		TASK_SET_DECISION_MAKER,
		TASK_SET_PED_SPHERE_DEFENSIVE_AREA,
		TASK_CLEAR_DEFENSIVE_AREA,
		TASK_GUARD_CURRENT_POS,
		TASK_USE_NEAREST_SCENARIO_TO_COORD,
		TASK_USE_NEAREST_SCENARIO_TO_COORD_WARP,
		TASK_USE_NEAREST_SCENARIO_CHAIN_TO_COORD,
		TASK_USE_NEAREST_SCENARIO_CHAIN_TO_COORD_WARP,
		TASK_RELOAD_WEAPON,
		TASK_VEHICLE_SHOOT_AT_PED,
		TASK_VEHICLE_AIM_AT_PED,
		TASK_VEHICLE_SHOOT_AT_COORD,
		TASK_VEHICLE_AIM_AT_COORD,
		TASK_FORCE_MOTION_STATE,
		TASK_GENERAL_SWEEP,
		TASK_ARREST_PED,
		TASK_GOTO_ENTITY,
		TASK_THROW_PROJECTILE,
		TASK_AIM_GUN_SCRIPTED,
		TASK_AIM_GUN_SCRIPTED_WITH_TARGET,
		TASK_AIM_GUN_AT_ENTITY,
		TASK_AIM_GUN_AT_COORD,
		TASK_SHOOT_GUN_AT_COORD,
		TASK_GOTO_ENTITY_OFFSET,
		TASK_GOTO_ENTITY_OFFSET_XY,
		TASK_VEHICLE_CHASE,
		TASK_SHOOT_AT_ENTITY,
		TASK_SEEK_COVER_FROM_POS,
		TASK_SEEK_COVER_FROM_PED,
		TASK_SEEK_COVER_TO_COVER_POINT,
		TASK_SEEK_COVER_TO_COVER_COORD,
		TASK_PUT_PED_DIRECTLY_INTO_COVER,
		TASK_WRITHE,
		TASK_MOVE_NETWORK,
		TASK_MOVE_NETWORK_ADVANCED,
		TASK_VEHICLE_PARK,
		TASK_VEHICLE_ESCORT,
		TASK_VEHICLE_FOLLOW,
		TASK_VEHICLE_HELI_PROTECT,
		TASK_VEHICLE_GOTO_NAVMESH,
		TASK_VEHICLE_FOLLOW_WAYPOINT_RECORDING,
		TASK_USE_MOBILE_PHONE,
		TASK_FOLLOW_NAV_MESH_TO_COORD_ADVANCED,
		TASK_VEHICLE_CRASH
	};

};

#endif